project:
  type: website
  output-dir: docs
  render:
    - "!CLAUDE.md"
    - "*.qmd"

website:
  title: "Darwin Del Castillo"
  navbar:
    right:
      - text: "About"
        href: about.qmd
      - text: "CV"
        href: cv.qmd
      - text: "Research"
        href: research.qmd
      - text: "Teaching"
        href: teaching.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css">